"""Initial migration

Revision ID: f1693a48bfc2
Revises: 
Create Date: 2025-07-12 12:18:19.940006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1693a48bfc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('googlelogin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notifications',
    sa.Column('nid', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('question',
    sa.Column('qid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    op.create_table('votes',
    sa.Column('vid', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('is_answer', sa.Boolean(), nullable=False),
    sa.Column('is_upvote', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('vid')
    )
    op.create_table('answers',
    sa.Column('aid', sa.UUID(), nullable=False),
    sa.Column('qid', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['qid'], ['question.qid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('ques_tag',
    sa.Column('qid', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['qid'], ['question.qid'], ),
    sa.PrimaryKeyConstraint('qid', 'tag')
    )
    op.create_table('comments',
    sa.Column('cid', sa.UUID(), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('aid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['answers.aid'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('ques_tag')
    op.drop_table('answers')
    op.drop_table('votes')
    op.drop_table('question')
    op.drop_table('notifications')
    op.drop_table('users')
    # ### end Alembic commands ###
